### ISSUE TITLE
Application Output error

### ISSUE THREAD

**Issue by JamesYopp** [ossuminc/riddl#495]
I am trying to define outputs for a dashboard page. I won't include all details to make it complete, but the relevant section can be seen below (this compiles):

```
page AOVDashboardPage {
  contains DashboardSideNav as group DashboardNav
  output AOVGraph shows record AOVData briefly "As a line graph"
  output AOVSummary shows record AggregatedAOV
  output OrderDetails shows record OrderDataTable 
  input TimeRangeSelector takes TimeRangeSelection
  input OrderMetricSelector takes OrderMetricSelection
}
```
I would expect that the third line could/should be written as:
`output AOVGraph shows graph AOVData briefly "As a line graph"`

Likewise, line 5 could/should be written as:
`output OrderDetails shows table OrderDataTable` 

However, when I make these changes I get an error like the following:
```
[error] Error: application/pages/dashboards/orderDashboards.riddl(24:35):
Expected one of ("}" | "input" | "form" | "text" | "button" | "picklist" | "selector" | "menu" | "output" | "document" | "list" | "table" | "graph" | "animation" | "picture" | "contains" | "group" | "page" | "pane" | "dialog" | "popup" | "frame" | "column" | "window" | "section" | "tab" | "flow" | "//" | "described" | "explained" | "briefly" | "brief" | "{" | "is" | "are" | ":" | "="):
  output OrderDetails shows table OrderDataTable
                                  ^
Context: (outputDefinitions | briefly | description | parse0$3 | parse0$1 | "}")
```

**Comment by reid-spencer** [comment]
RIDDL's type system does not support tables or graphs because these can be constructed from existing types. 

For example a table could be constructed like this:
```
record Row is { a: String, b: String, c: String }
type Table is Row*
```

Similarly a graph can be constructed using references. 

Or are you merely suggesting that table and graph be included as synonyms for types? If so, what's wrong with:
```
output AOVGraph shows AOVDataGraph briefly "As a line graph"
output OrderDetails shows OrderDataTable 
```
where AOVDataGraph is a type name ?

**Comment by JamesYopp** [comment]
Perhaps I am just confused. I am still figuring out this application specification part of RIDDL. Creating bounded contexts and entities comes so much more naturally to me. All of my recent page definitions carry this basic syntax

output <name1> <verb> <kind> <name2>
where name1 and name2 are unique identifiers in the RIDDL specification. I have an output named name1. I have a record named name2. and so on.
where verb is some action (shows, presents, writes, emits, displays) (all keywords in RIDDL)
and where kind is another RIDDL keyword dictating the kind of output. The error message included in the description lists these things out (input, form, text, button, ..., list, table, graph, ...)
So, part of the reason for this issue is it seemed that RIDDL was _expecting_ table or graph (at least how I interpreted the error message), but it was erroring when trying to use it. I did not include all the details to make the sample in the description complete, but the way you suggested constructing a table or a graph is exactly the way I had specified the types. What you are saying then is the "kind" part of an output is optional. I can use "record" as I did in the example or omit it. I have validated that it works both ways.

On closer inspection the "kind" keyword I was using in many of these statements - "record" - as in:
`output AOVGraph shows record AOVData briefly "As a line graph"`
isn't required and it does not show up as a keyword in the list presented by the error message.

I hope this all makes sense.

**Comment by reid-spencer** [comment]
@JamesYopp 
The `{kind}` part of your example is a strict set of keywords to identify a RIDDL type with a path Identifier (e.g. `{name2}`). Originally there was just "type" and then we added message distinctions (command, event, query, result). In the resolution to this, we have now added two more kinds of types, `graph` and `table`. So you can now do things like:
```
type MyGraph is graph of String
type MyTable is table of String of [4,4]
```
The intention of this, respectively are:
* MyGraph is an acyclic graph of nodes that contain just a String
* MyTable is a 4x4 matrix of Strings; you can have 1 or more dimensions on a "table"

Additionally, this PR implements keyword/structure checking. That is, if you do something like:
```
output Foo shows graph MyGraph
```
then the path identifier (MyGraph) must actually be the definition of a Graph type, and that is checked. Same for Tables and messages. So, the `{kind}` keyword is now semantically validated as well. 

> So, part of the reason for this issue is it seemed that RIDDL was expecting table or graph (at least how I interpreted the error message),

That interpretation was incorrect. RIDDL has *never* expected table or graph as type kinds until this issue was resolved

>  but it was erroring when trying to use it. 

because it wasn't actually expected :)

> I did not include all the details to make the sample in the description complete, but the way you suggested constructing a table or a graph is exactly the way I had specified the types. 

Fair enough. I went ahead and added two new TypeExpression kinds for them to make this more clear. I figured it was easier for the user than constructs like:
```
type MyTableRow is String+
type MyTable is MyTableRow+
```
because that is dimensionless and verbose. In particular graphs can be constructed in many ways involving node to node references and compete with mapping (a more restrictive form of graph) so I decided to just provide a syntax for the most common kind of graph, acyclic directed.  About the only thing missing now is a Tensor and a few other data types from advanced mathematics that few would use. 

> What you are saying then is the "kind" part of an output is optional. 

It has always been optional. If you leave it out, it will be regarded as "type" which is a catch-all for "any type" and that will work in many cases but there are some situations where the validator expects a specific kind of type and you'll get an error if that is violated by using nothing or "type". For example if you use a "type" that references, say, a String in a handler's "On Clause", which requires a message type, you'll get an error. 

> I can use "record" as I did in the example or omit it. I have validated that it works both ways.

Correct, in many cases.  You can also use: type, command, event, result, query, graph, and table. The advantage of using the "kind" prefix, now that this issue is resolved, is that it will check that the path you used actually refers to such a type definition

> On closer inspection the "kind" keyword I was using in many of these statements - "record" - as in:
> output AOVGraph shows record AOVData briefly "As a line graph"
> isn't required and it does not show up as a keyword in the list presented by the error message.

That's correct, it isn't required in any type reference you make anywhere in the language; BUT, I would highly encourage it because of the extra semantic validation that occurs. 

> I hope this all makes sense.

It does. I hope my answer makes sense to you :)
