### ISSUE TITLE
[DEFECT] CommonOptions not available when formatting outside a PC

### ISSUE THREAD

**Issue by AlexWeinstein92** [ossuminc/riddl#697]
### **Symptom**
After each run, the plugin saves the Messages that come back from `runCommandWithArgs`
These messages do not respect the check for commonOptions.noANSIMessages because the options are not passed into the `format` function or its downstream `annotateErrorLine` function

### **Expected Behavior**
NoANSIMessages, and all other CommonOptions, should appropriately affect `Messages.format` even outside of a `PlatformContext`

### **Steps To Reproduce**
List the steps to reproduce the symptomatic behavior:
1. Inspect the output `Messages` of `runcommandWithArgs` and note that ANSI formatting codes are still present even when `noANSIMessages = true`

**Comment by reid-spencer** [comment]
@AlexWeinstein92 - do you concur?

**Comment by reid-spencer** [comment]
There are only two modules that import scala.io.AnsiColor and therefore only two modules that could possibly insert ANSI highlighting. those modules are `utils.Logging` and `language.parsing.RiddlParserInput`. Consequently, the `Message.format` method does not need to have checks for noANSIMessages in it.  That method does call RiddlParserInput. annotateErrorLines but its use of ANSI highlighting is guarded by a check on noANSIMessages.

The only use of ANSI highlighting in the Logger occurs in the `highlight` method which uses an appropriate noANSIMessages highlight to guard the highlighting of the message.

The "actual String holding the message" can only be generated from the Parser or validation routines and they never insert ANSI highlighting because they never import scala.io.AnsiColor.

Consequently, I hold that no ANSI highlighting is being done without heeding the noANSIMessages setting in CommonOptions. If this occurs for you, it must necessarily be the setting of noANSIMessages you've placed in your given statements.

**Comment by AlexWeinstein92** [comment]
Turns out a refactoring I did is another branch. My current branch uses an old method of producing console output. Apologies for the confusion
